import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
<nav style={{ display: "flex", gap: 16, marginBottom: 24 }}>
  <a href="/sections">Sections</a>
  <a href="/units">1. Units & rubrics</a>
  <a href="/marks">2. Enter marks</a>
  <a href="/generate">3. Generate & export</a>
  <a href="/students">Students</a>
  <a href="/quarters">Quarters</a>
  <a href="/marks">2. Enter marks</a>
</nav>